name: Test deployment (minimum validations)

on:
  workflow_call:
    inputs:
      playbook-name:
        default: 'playbook-local.yml'
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  test-deploy:
    name: Test deployment (minimum validations)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout helper scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: rancher/product-docs-common
          ref: main
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false
          path: helpers

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
      
      - name: Check revdate
        uses: rancher/product-docs-common/.github/actions/check-revdate-composite-action@bef76c9aab79980088a221e72e006acd3bfd8257
        with:
          token: ${{ secrets.token }}

      - name: Install Antora and dependencies
        run: make environment

      - name: Check for broken symlinks
        uses: rancher/product-docs-common/.github/actions/check-symlinks-composite-action@776dee012d9ab2f661cdbdeeb16e6ab81e965d5a

      - name: Generate Site
        run: |
          npx antora --stacktrace \
            --log-format=pretty \
            --log-level=info \
            ${{ inputs.playbook-name }}
            
