name: Test deployment (minimum validations)

on:
  workflow_call:
    inputs:
      playbook-name:
        default: 'playbook-local.yml'
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  test-deploy:
    name: Test deployment (minimum validations)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout helper scripts
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: rancher/product-docs-common
          ref: main
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false
          path: helpers

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
      
      - name: Check revdate
        uses: rancher/product-docs-common/.github/actions/check-revdate-composite-action@bef76c9aab79980088a221e72e006acd3bfd8257
        with:
          token: ${{ secrets.token }}

      - name: Install Antora and dependencies
        run: make environment

      - name: Check for broken symlinks
        uses: rancher/product-docs-common/.github/actions/check-symlinks-composite-action@6da2db6b0b9d098f1cd540aa6e076865365497a4

      - name: Generate Site
        run: |
          npx antora --stacktrace \
            --log-format=pretty \
            --log-level=info \
            ${{ inputs.playbook-name }}
            
